#!/bin/sh
# Can Kandemir: cnkndmr@gmail.com
# shows the percentage of brightness
# left click sets brightness to 100%
# middle click sets brightness to 50%
# right click sets brightness to 0%
# scroll up/down changes brightness by +-5%

case $BLOCK_BUTTON in
	1) xbacklight -set 100 && pkill -RTMIN+13 i3blocks ;;
	2) xbacklight -set 51 && pkill -RTMIN+13 i3blocks ;;
	3) xbacklight -set 0 && pkill -RTMIN+13 i3blocks ;;
	4) xbacklight -inc 5% && pkill -RTMIN+13 i3blocks ;; # scroll up, increase
	5) xbacklight -dec 5% && pkill -RTMIN+13 i3blocks ;; # scroll down, decrease
esac

echo $(xbacklight | sed 's/\..*//')%
