#!/bin/sh
# Can Kandemir: cnkndmr@gmail.com
# shows the cpu load
# changes color if load above 75% and 100%

case $BLOCK_BUTTON in
	1) mate-terminal -e htop;;
esac

LOAD=$(cat /proc/loadavg | awk -vnproc=$(nproc) '{print $1/nproc}')
LOAD_RAT=$(cat /proc/loadavg | awk -vnproc=$(nproc) '{print $1/nproc*100}')
LOAD_RAT_INT=$(printf '%.0f\n' $LOAD_RAT)

COLOR='<span color="#FF0000">'
[ $LOAD_RAT_INT -le 100 ] && COLOR='<span color="#FFFF00">'
[ $LOAD_RAT_INT -le 75 ] && COLOR='<span color="#00FF00">'

#echo $COLOR$LOAD'</span>'
echo $COLOR$(printf "%0.2f" $LOAD)'</span>'
