#!/bin/sh

case $BLOCK_BUTTON in
	1) pulsemixer --set-volume 100 && pkill -RTMIN+12 i3blocks ;;
	2) pulsemixer --set-volume 50 && pkill -RTMIN+12 i3blocks ;;
	3) pulsemixer --set-volume 0 && pkill -RTMIN+12 i3blocks ;;
	4) pulsemixer --change-volume +5 && pkill -RTMIN+12 i3blocks ;;
	5) pulsemixer --change-volume -5 && pkill -RTMIN+12 i3blocks ;;
#	3) pgrep -x dunst >/dev/null && notify-send "📢 Volume module" "\- Shows volume 🔊, 🔇 if muted.
#- Middle click to mute.
#- Scroll to change."
esac

[ "$(pulsemixer --get-mute)" = "1" ] && echo "MUTE" && exit

echo $(pulsemixer --get-volume | awk '{print $1}')%
