#!/bin/sh
# Can Kandemir: cnkndmr@gmail.com
# apt block shows the count of upgradable packages.
# left click shows the upgradable packages at notification area

case $BLOCK_BUTTON in
	1) notify-send "Upgradable package list" "$(apt list --upgradable | awk '{print $1}' | cut -c -55)" ;;
esac

APT=$(( $(apt list --upgradable | wc -l) - 1 ))
REBOOT=$(cat /var/run/reboot-required | wc -l)
#APT=12
#REBOOT=1

[ $REBOOT -eq 1 ] && echo '<span color="#FF0000">Reboot Required</span>'
[ $APT -ne 0 ] && echo '<span color="#00FF00">'$APT'</span>'
echo
